FROM python:3.8
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /replica

RUN mkdir /replica
COPY ./requirements /replica/requirements
COPY ./tests /replica/tests
COPY ./integration_tests /replica/integration_tests
ADD integration_tests/manage.py /replica/

RUN pip install -r /replica/requirements/dev.txt -r /replica/requirements/test.txt \
    && pip install psycopg2-binary django-cqrs==1.3.1

WORKDIR /replica/
